export const QUESTION_BANK = [
    {
        id: 'q1',
        text: 'Qual é o principal benefício de usar "Server Actions" no Next.js?',
        options: [
            { id: 'a', text: 'Melhorar o SEO automaticamente' },
            { id: 'b', text: 'Executar código no servidor diretamente de componentes' },
            { id: 'c', text: 'Criar animações CSS complexas' },
            { id: 'd', text: 'Substituir o React Context' },
        ],
        correctId: 'b',
    },
    {
        id: 'q2',
        text: 'O que o Prisma ORM facilita no desenvolvimento?',
        options: [
            { id: 'a', text: 'Renderização de componentes 3D' },
            { id: 'b', text: 'Interação type-safe com o banco de dados' },
            { id: 'c', text: 'Minificação de arquivos CSS' },
            { id: 'd', text: 'Gerenciamento de estado global no cliente' },
        ],
        correctId: 'b',
    },
    {
        id: 'q3',
        text: 'Para que serve o "use client" no Next.js App Router?',
        options: [
            { id: 'a', text: 'Para marcar um componente como Client Component' },
            { id: 'b', text: 'Para importar bibliotecas do cliente' },
            { id: 'c', text: 'Para usar hooks do React no servidor' },
            { id: 'd', text: 'Para otimizar imagens' },
        ],
        correctId: 'a',
    },
    {
        id: 'q4',
        text: 'Qual hook é usado para gerenciar estado local no React?',
        options: [
            { id: 'a', text: 'useEffect' },
            { id: 'b', text: 'useState' },
            { id: 'c', text: 'useContext' },
            { id: 'd', text: 'useReducer' },
        ],
        correctId: 'b',
    },
    {
        id: 'q5',
        text: 'O que é "Hydration" no contexto de SSR?',
        options: [
            { id: 'a', text: 'O processo de carregar CSS' },
            { id: 'b', text: 'Anexar event listeners ao HTML estático' },
            { id: 'c', text: 'Fazer download de imagens' },
            { id: 'd', text: 'Conectar ao banco de dados' },
        ],
        correctId: 'b',
    },
    {
        id: 'q6',
        text: 'O que significa NFT?',
        options: [
            { id: 'a', text: 'New File Type' },
            { id: 'b', text: 'Non-Fungible Token' },
            { id: 'c', text: 'Network File Transfer' },
            { id: 'd', text: 'No Fee Transaction' },
        ],
        correctId: 'b',
    },
    {
        id: 'q7',
        text: 'Qual destas é uma linguagem de Smart Contracts?',
        options: [
            { id: 'a', text: 'Python' },
            { id: 'b', text: 'Solidity' },
            { id: 'c', text: 'Java' },
            { id: 'd', text: 'C++' },
        ],
        correctId: 'b',
    },
    {
        id: 'q8',
        text: 'O que é TailwindCSS?',
        options: [
            { id: 'a', text: 'Um framework JavaScript' },
            { id: 'b', text: 'Uma biblioteca de componentes prontos' },
            { id: 'c', text: 'Um framework CSS utility-first' },
            { id: 'd', text: 'Um pré-processador como SASS' },
        ],
        correctId: 'c',
    },
    {
        id: 'q9',
        text: 'Qual o comando para criar um novo projeto Next.js?',
        options: [
            { id: 'a', text: 'npm create-react-app' },
            { id: 'b', text: 'npx create-next-app' },
            { id: 'c', text: 'npm install next' },
            { id: 'd', text: 'next new project' },
        ],
        correctId: 'b',
    },
    {
        id: 'q10',
        text: 'O que é "Gas" na rede Ethereum?',
        options: [
            { id: 'a', text: 'Combustível para servidores' },
            { id: 'b', text: 'Taxa paga para processar transações' },
            { id: 'c', text: 'Token de governança' },
            { id: 'd', text: 'Erro de rede' },
        ],
        correctId: 'b',
    },
    {
        id: 'q11',
        text: 'Qual hook do React é usado para efeitos colaterais?',
        options: [
            { id: 'a', text: 'useState' },
            { id: 'b', text: 'useMemo' },
            { id: 'c', text: 'useEffect' },
            { id: 'd', text: 'useCallback' },
        ],
        correctId: 'c',
    },
    {
        id: 'q12',
        text: 'O que é uma "Wallet" na Web3?',
        options: [
            { id: 'a', text: 'Um banco digital' },
            { id: 'b', text: 'Uma ferramenta para gerenciar chaves privadas e assinar transações' },
            { id: 'c', text: 'Um site de câmbio' },
            { id: 'd', text: 'Um arquivo de texto com senhas' },
        ],
        correctId: 'b',
    },
    {
        id: 'q13',
        text: 'Qual tag HTML é usada para links internos no Next.js?',
        options: [
            { id: 'a', text: '<a>' },
            { id: 'b', text: '<Link>' },
            { id: 'c', text: '<NavLink>' },
            { id: 'd', text: '<RouterLink>' },
        ],
        correctId: 'b',
    },
    {
        id: 'q14',
        text: 'O que é "Responsive Design"?',
        options: [
            { id: 'a', text: 'Design que responde a comandos de voz' },
            { id: 'b', text: 'Design que se adapta a diferentes tamanhos de tela' },
            { id: 'c', text: 'Design com animações rápidas' },
            { id: 'd', text: 'Design feito por IA' },
        ],
        correctId: 'b',
    },
    {
        id: 'q15',
        text: 'Qual é a função do arquivo "layout.tsx" no Next.js?',
        options: [
            { id: 'a', text: 'Definir rotas da API' },
            { id: 'b', text: 'Compartilhar UI entre múltiplas páginas' },
            { id: 'c', text: 'Configurar o banco de dados' },
            { id: 'd', text: 'Estilizar componentes globais' },
        ],
        correctId: 'b',
    },
    {
        id: 'q16',
        text: 'O que é "Prop Drilling" no React?',
        options: [
            { id: 'a', text: 'Uma técnica de animação 3D' },
            { id: 'b', text: 'Passar dados por muitos níveis de componentes manuais' },
            { id: 'c', text: 'Uma ferramenta de build' },
            { id: 'd', text: 'Um novo método de ciclo de vida' },
        ],
        correctId: 'b',
    },
    {
        id: 'q17',
        text: 'Qual a diferença entre "interface" e "type" no TypeScript?',
        options: [
            { id: 'a', text: 'Não há diferença nenhuma' },
            { id: 'b', text: 'Interfaces são apenas para classes' },
            { id: 'c', text: 'Interfaces são extensíveis (open-ended), types não' },
            { id: 'd', text: 'Types não suportam união (|)' },
        ],
        correctId: 'c',
    },
    {
        id: 'q18',
        text: 'Para que serve o "Z-Index" no CSS?',
        options: [
            { id: 'a', text: 'Controlar a transparência' },
            { id: 'b', text: 'Controlar a ordem de empilhamento (eixo Z)' },
            { id: 'c', text: 'Aumentar o tamanho da fonte' },
            { id: 'd', text: 'Criar layouts flexíveis' },
        ],
        correctId: 'b',
    },
    {
        id: 'q19',
        text: 'O que é um "DAO" na Web3?',
        options: [
            { id: 'a', text: 'Data Access Object' },
            { id: 'b', text: 'Digital Art Organization' },
            { id: 'c', text: 'Decentralized Autonomous Organization' },
            { id: 'd', text: 'Dynamic App Optimization' },
        ],
        correctId: 'c',
    },
    {
        id: 'q20',
        text: 'Qual tag HTML é semanticamente correta para o conteúdo principal da página?',
        options: [
            { id: 'a', text: '<div>' },
            { id: 'b', text: '<section>' },
            { id: 'c', text: '<main>' },
            { id: 'd', text: '<article>' },
        ],
        correctId: 'c',
    },
    {
        id: 'q21',
        text: 'O que o comando "git commit" faz?',
        options: [
            { id: 'a', text: 'Envia arquivos para o servidor remoto' },
            { id: 'b', text: 'Salva as mudanças no histórico local' },
            { id: 'c', text: 'Baixa atualizações do repositório' },
            { id: 'd', text: 'Cria uma nova branch' },
        ],
        correctId: 'b',
    },
    {
        id: 'q22',
        text: 'Qual método HTTP é usado para ATUALIZAR recursos?',
        options: [
            { id: 'a', text: 'GET' },
            { id: 'b', text: 'POST' },
            { id: 'c', text: 'PUT / PATCH' },
            { id: 'd', text: 'DELETE' },
        ],
        correctId: 'c',
    },
    {
        id: 'q23',
        text: 'O que é "Lazy Loading"?',
        options: [
            { id: 'a', text: 'Um bug de performance' },
            { id: 'b', text: 'Carregar recursos apenas quando necessários' },
            { id: 'c', text: 'Um padrão de design preguiçoso' },
            { id: 'd', text: 'Carregar tudo de uma vez' },
        ],
        correctId: 'b',
    },
    {
        id: 'q24',
        text: 'Qual a principal vantagem do SVG sobre PNG?',
        options: [
            { id: 'a', text: 'Tem milhões de cores' },
            { id: 'b', text: 'Pode ser animado e não perde qualidade ao escalar' },
            { id: 'c', text: 'É sempre menor em bytes' },
            { id: 'd', text: 'Suporta transparência (PNG não suporta)' },
        ],
        correctId: 'b',
    },
    {
        id: 'q26',
        text: 'Qual é o foco principal da metodologia "Agile"?',
        options: [
            { id: 'a', text: 'Documentação extensiva' },
            { id: 'b', text: 'Entrega contínua e feedback rápido' },
            { id: 'c', text: 'Seguir o plano original a todo custo' },
            { id: 'd', text: 'Evitar mudanças no escopo' },
        ],
        correctId: 'b',
    },
    {
        id: 'q27',
        text: 'O que é "Phishing"?',
        options: [
            { id: 'a', text: 'Uma técnica de otimização de banco de dados' },
            { id: 'b', text: 'Um ataque de engenharia social para roubar credenciais' },
            { id: 'c', text: 'Um framework de testes' },
            { id: 'd', text: 'Uma biblioteca de gráficos em Python' },
        ],
        correctId: 'b',
    },
    {
        id: 'q28',
        text: 'Qual comando SQL é usado para recuperar dados?',
        options: [
            { id: 'a', text: 'UPDATE' },
            { id: 'b', text: 'DELETE' },
            { id: 'c', text: 'SELECT' },
            { id: 'd', text: 'INSERT' },
        ],
        correctId: 'c',
    },
    {
        id: 'q29',
        text: 'O que é um "Container" (ex: Docker)?',
        options: [
            { id: 'a', text: 'Uma máquina virtual completa com sistema operacional' },
            { id: 'b', text: 'Um pacote leve que contém tudo para rodar o software' },
            { id: 'c', text: 'Um tipo de variável em Java' },
            { id: 'd', text: 'Um componente de UI' },
        ],
        correctId: 'b',
    },
    {
        id: 'q30',
        text: 'Na comunicação assertiva, o foco deve ser:',
        options: [
            { id: 'a', text: 'Ganhar a discussão' },
            { id: 'b', text: 'Expressar necessidades de forma clara e respeitosa' },
            { id: 'c', text: 'Ser passivo para evitar conflitos' },
            { id: 'd', text: 'Ser agressivo para demonstrar liderança' },
        ],
        correctId: 'b',
    },
    {
        id: 'q31',
        text: 'O que significa SEO?',
        options: [
            { id: 'a', text: 'Server Error Optimization' },
            { id: 'b', text: 'Search Engine Optimization' },
            { id: 'c', text: 'Secure External Object' },
            { id: 'd', text: 'Site Entry Organization' },
        ],
        correctId: 'b',
    },
    {
        id: 'q32',
        text: 'Qual é a função do "funil de vendas"?',
        options: [
            { id: 'a', text: 'Filtrar emails de spam' },
            { id: 'b', text: 'Mapear a jornada do cliente da descoberta à compra' },
            { id: 'c', text: 'Calcular impostos automaticamente' },
            { id: 'd', text: 'Gerenciar estoque' },
        ],
        correctId: 'b',
    },
    {
        id: 'q33',
        text: 'O que é "Machine Learning"?',
        options: [
            { id: 'a', text: 'Ensinar robôs a andar' },
            { id: 'b', text: 'Algoritmos que melhoram com a experiência (dados)' },
            { id: 'c', text: 'Programação de baixo nível' },
            { id: 'd', text: 'Manutenção de hardware' },
        ],
        correctId: 'b',
    },
    {
        id: 'q34',
        text: 'Qual destes é um banco de dados NoSQL?',
        options: [
            { id: 'a', text: 'MySQL' },
            { id: 'b', text: 'PostgreSQL' },
            { id: 'c', text: 'MongoDB' },
            { id: 'd', text: 'Oracle' },
        ],
        correctId: 'c',
    },
    {
        id: 'q35',
        text: 'O que é "CI/CD"?',
        options: [
            { id: 'a', text: 'Code Inspection / Code Deletion' },
            { id: 'b', text: 'Continuous Integration / Continuous Delivery' },
            { id: 'c', text: 'Central Interface / Command Domain' },
            { id: 'd', text: 'Customer Insight / Customer Data' },
        ],
        correctId: 'b',
    },
    {
        id: 'q36',
        text: 'Qual é o princípio "DRY" na programação?',
        options: [
            { id: 'a', text: 'Do Repeat Yourself' },
            { id: 'b', text: 'Don\'t Repeat Yourself' },
            { id: 'c', text: 'Data Recovery Yield' },
            { id: 'd', text: 'Deploy Right Yesterday' },
        ],
        correctId: 'b',
    },
    {
        id: 'q37',
        text: 'O que é autenticação 2FA?',
        options: [
            { id: 'a', text: 'Login com duas senhas iguais' },
            { id: 'b', text: 'Autenticação de Dois Fatores' },
            { id: 'c', text: 'Acesso para dois usuários' },
            { id: 'd', text: 'Protocolo de internet' },
        ],
        correctId: 'b',
    },
    {
        id: 'q38',
        text: 'Qual métrica mede o retorno sobre investimento?',
        options: [
            { id: 'a', text: 'KPI' },
            { id: 'b', text: 'ROI' },
            { id: 'c', text: 'CPC' },
            { id: 'd', text: 'CTR' },
        ],
        correctId: 'b',
    },
    {
        id: 'q39',
        text: 'O que é um "MVP"?',
        options: [
            { id: 'a', text: 'Most Valuable Player' },
            { id: 'b', text: 'Minimum Viable Product' },
            { id: 'c', text: 'Maximum Value Protocol' },
            { id: 'd', text: 'Minor Version Patch' },
        ],
        correctId: 'b',
    },
    {
        id: 'q40',
        text: 'Qual linguagem é conhecida pelo uso em Data Science?',
        options: [
            { id: 'a', text: 'HTML' },
            { id: 'b', text: 'Python' },
            { id: 'c', text: 'CSS' },
            { id: 'd', text: 'PHP' },
        ],
        correctId: 'b',
    },
    {
        id: 'q41',
        text: 'O que significa "Full Stack"?',
        options: [
            { id: 'a', text: 'Um desenvolvedor que trabalha apenas com banco de dados' },
            { id: 'b', text: 'Um desenvolvedor que domina Frontend e Backend' },
            { id: 'c', text: 'Uma pilha cheia de erros' },
            { id: 'd', text: 'Um framework de CSS' },
        ],
        correctId: 'b',
    },
    {
        id: 'q42',
        text: 'O que é "Latency" (Latência)?',
        options: [
            { id: 'a', text: 'A largura de banda da rede' },
            { id: 'b', text: 'O tempo de atraso na transmissão de dados' },
            { id: 'c', text: 'O tamanho do arquivo' },
            { id: 'd', text: 'A força do sinal Wi-Fi' },
        ],
        correctId: 'b',
    },
    {
        id: 'q43',
        text: 'Qual destes é um serviço de nuvem (Cloud)?',
        options: [
            { id: 'a', text: 'Microsoft Word Office 2010' },
            { id: 'b', text: 'AWS (Amazon Web Services)' },
            { id: 'c', text: 'Pen Drive' },
            { id: 'd', text: 'CD-ROM' },
        ],
        correctId: 'b',
    },
    {
        id: 'q44',
        text: 'O que é "Scrum"?',
        options: [
            { id: 'a', text: 'Um tipo de café' },
            { id: 'b', text: 'Um framework ágil para gestão de projetos' },
            { id: 'c', text: 'Uma linguagem de programação antiga' },
            { id: 'd', text: 'Um vírus de computador' },
        ],
        correctId: 'b',
    },
    {
        id: 'q45',
        text: 'O que é um "Token de Governança"?',
        options: [
            { id: 'a', text: 'Uma senha de administrador' },
            { id: 'b', text: 'Um token que dá direito a voto em uma DAO' },
            { id: 'c', text: 'Uma moeda usada apenas para pagar taxas' },
            { id: 'd', text: 'Um NFT de arte' },
        ],
        correctId: 'b',
    },
    {
        id: 'q46',
        text: 'Qual é a principal característica do Blockchain?',
        options: [
            { id: 'a', text: 'Centralização' },
            { id: 'b', text: 'Imutabilidade e Descentralização' },
            { id: 'c', text: 'Velocidade superior a SQL' },
            { id: 'd', text: 'Facilidade de editar registros passados' },
        ],
        correctId: 'b',
    },
    {
        id: 'q47',
        text: 'O que é "Soft Skill"?',
        options: [
            { id: 'a', text: 'Habilidade técnica (ex: Java)' },
            { id: 'b', text: 'Habilidade comportamental (ex: Inteligência Emocional)' },
            { id: 'c', text: 'Software leve' },
            { id: 'd', text: 'Habilidade de design' },
        ],
        correctId: 'b',
    },
    {
        id: 'q48',
        text: 'O que é "Open Source"?',
        options: [
            { id: 'a', text: 'Software pago' },
            { id: 'b', text: 'Software com código-fonte aberto e livre para modificação' },
            { id: 'c', text: 'Software que nunca falha' },
            { id: 'd', text: 'Software pirata' },
        ],
        correctId: 'b',
    },
    {
        id: 'q49',
        text: 'Qual o objetivo do teste A/B?',
        options: [
            { id: 'a', text: 'Testar se o site está online' },
            { id: 'b', text: 'Comparar duas versões para ver qual performa melhor' },
            { id: 'c', text: 'Testar o código em dois navegadores' },
            { id: 'd', text: 'Verificar a segurança do servidor' },
        ],
        correctId: 'b',
    },
    {
        id: 'q50',
        text: 'O que é "Burnout"?',
        options: [
            { id: 'a', text: 'Uma técnica de programação extrema' },
            { id: 'b', text: 'Esgotamento profissional físico e mental' },
            { id: 'c', text: 'Uma ferramenta de benchmarking' },
            { id: 'd', text: 'Um novo framework JavaScript' },
        ],
        correctId: 'b',
    },
    {
        id: 'q51',
        text: 'Para que serve o "Gitignore"?',
        options: [
            { id: 'a', text: 'Para ignorar erros de compilação' },
            { id: 'b', text: 'Para especificar arquivos que não devem ser versionados' },
            { id: 'c', text: 'Para deletar o repositório' },
            { id: 'd', text: 'Para ignorar usuários tóxicos' },
        ],
        correctId: 'b',
    },
    {
        id: 'q52',
        text: 'O que é JSON?',
        options: [
            { id: 'a', text: 'Java Source Object Network' },
            { id: 'b', text: 'JavaScript Object Notation' },
            { id: 'c', text: 'Junior Senior Object Name' },
            { id: 'd', text: 'Just Some Other Notation' },
        ],
        correctId: 'b',
    },
    {
        id: 'q53',
        text: 'Qual destes é um framework Frontend?',
        options: [
            { id: 'a', text: 'Laravel' },
            { id: 'b', text: 'Django' },
            { id: 'c', text: 'Vue.js' },
            { id: 'd', text: 'Spring Boot' },
        ],
        correctId: 'c',
    },
    {
        id: 'q54',
        text: 'O que é "Cold Start" em Serverless?',
        options: [
            { id: 'a', text: 'Ligar o ar condicionado do servidor' },
            { id: 'b', text: 'O atraso na primeira execução de uma função inativa' },
            { id: 'c', text: 'Iniciar o computador no inverno' },
            { id: 'd', text: 'Um erro de rede' },
        ],
        correctId: 'b',
    },
    {
        id: 'q55',
        text: 'Qual a principal função do DNS?',
        options: [
            { id: 'a', text: 'Proteger contra vírus' },
            { id: 'b', text: 'Traduzir nomes de domínio (ex: google.com) para IPs' },
            { id: 'c', text: 'Acelerar o download' },
            { id: 'd', text: 'Armazenar emails' },
        ],
        correctId: 'b',
    }
];

export function getRandomQuestion() {
    return QUESTION_BANK[Math.floor(Math.random() * QUESTION_BANK.length)];
}

export function getQuestionById(id: string) {
    return QUESTION_BANK.find(q => q.id === id);
}
